# Site settings
title: Marcel van Workum
email:
description: "Notes on software development and life."
baseurl: ""
url: "http://marcelvanworkum.github.io"
twitter_username: marcelvanworkum
github_username: marcelvanworkum

# Build settings
markdown: kramdown
permalink: pretty
google_analytics: "G-Q459DVJJQ2"

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
