title: Marcel van Workums's Blog
author: Marcel van Workum
email:
description: Notes on software development and life.
url: "https://marcelvanworkum.com/"
# url: "http://marcelvanworkum.github.io"

# Build settings
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed
google_analytics: "G-Q459DVJJQ2"

moving:
  about_you: Notes on software development and life.
  avatar_url: avatar.jpeg
  date_format: "%b %d"
  back_to: "Index"
  social_links:
    rss: RSS
    github: marcelvanworkum
    # linkedin:
